package task

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/juststeveking/flow/internal/core"
)

// TASKS.md is a generated board grouped by status. It is derived, never truth
// (adr-0001): a merge conflict in it is resolved by regenerating, not merging,
// which is why the header says so and why .gitattributes marks it -diff.

// indexStatusOrder is the fixed group order: active work first, terminal last.
var indexStatusOrder = []Status{
	StatusDoing, StatusReview, StatusBlocked, StatusTodo, StatusDone, StatusDropped,
}

const indexHeader = "<!-- Generated by flow. Do not edit. Run `flow task sync`.\n" +
	"     Derived from .flow/tasks/; resolve a merge conflict by regenerating, not merging. -->\n"

// IndexPath is the location of the generated board for a project root.
func IndexPath(root string) string {
	return filepath.Join(root, ".flow", "TASKS.md")
}

// RenderIndex builds TASKS.md bytes. It is a pure function of the set, so running
// sync twice with no change produces identical bytes. Empty status groups are
// omitted; within a group tasks are id-ordered (All is id-ordered).
func RenderIndex(set *TaskSet) []byte {
	buckets := map[Status][]*Task{}
	for _, t := range set.All() {
		buckets[t.Status] = append(buckets[t.Status], t)
	}
	var b bytes.Buffer
	b.WriteString(indexHeader)
	for _, st := range indexStatusOrder {
		group := buckets[st]
		if len(group) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n", titleCase(st))
		for _, t := range group {
			done, total, _ := t.Progress()
			file := filepath.Base(t.Path)
			fmt.Fprintf(&b, "- [%s](tasks/%s) %s `%d/%d`", t.ID, file, t.Title, done, total)
			if name := assigneeName(t); name != "" {
				fmt.Fprintf(&b, " @%s", name)
			}
			b.WriteByte('\n')
		}
	}
	return b.Bytes()
}

// PlanIndex loads the task set and prepares an atomic write of TASKS.md, so callers
// reuse core.Store.Apply and the commit path. Regenerate after any mutating command.
func PlanIndex(root string) (core.WriteOp, error) {
	set, err := LoadTasks(root)
	if err != nil {
		return core.WriteOp{}, err
	}
	op := core.WriteOp{AbsPath: IndexPath(root), After: RenderIndex(set)}
	before, rerr := os.ReadFile(op.AbsPath)
	if rerr != nil {
		if !os.IsNotExist(rerr) {
			return core.WriteOp{}, rerr
		}
		op.New = true
	} else {
		op.Before = before
	}
	return op, nil
}

// titleCase upper-cases the first letter of a status for a group heading.
func titleCase(s Status) string {
	if s == "" {
		return ""
	}
	r := []rune(string(s))
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] -= 'a' - 'A'
	}
	return string(r)
}

// assigneeName strips the agent:/human: prefix for the compact @name on the board.
func assigneeName(t *Task) string {
	if t.Assignee == "" {
		return ""
	}
	for i := 0; i < len(t.Assignee); i++ {
		if t.Assignee[i] == ':' {
			return t.Assignee[i+1:]
		}
	}
	return t.Assignee
}
