package task

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// planTaskFile writes a raw task document into root's tasks dir.
func planTaskFile(t *testing.T, root, name, doc string) {
	t.Helper()
	dir := TasksDir(root)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, name), []byte(doc), 0o644); err != nil {
		t.Fatal(err)
	}
}

const doingDoc = `---
id: T-014
title: Rate limit the ingestion endpoint
status: doing
assignee: agent:claude
created: 2026-08-01
updated: 2026-08-01
---
## Acceptance criteria
- [x] a
- [ ] b
- [ ] c
`

const todoDoc = `---
id: T-015
title: Problem+JSON error envelope
status: todo
created: 2026-08-01
updated: 2026-08-01
---
## Acceptance criteria
- [ ] a
- [ ] b
- [ ] c
- [ ] d
`

const doneDoc = `---
id: T-002
title: Old finished thing
status: done
created: 2026-08-01
updated: 2026-08-01
---
## Acceptance criteria
- [x] done
`

func TestRenderIndexGroupedAndFormatted(t *testing.T) {
	root := t.TempDir()
	planTaskFile(t, root, "T-014-rate-limit-ingestion.md", doingDoc)
	planTaskFile(t, root, "T-015-problem-json-envelope.md", todoDoc)
	planTaskFile(t, root, "T-002-old.md", doneDoc)

	set, err := LoadTasks(root)
	if err != nil {
		t.Fatal(err)
	}
	got := string(RenderIndex(set))

	if !strings.HasPrefix(got, "<!-- Generated by flow.") {
		t.Fatalf("missing generated header:\n%s", got)
	}
	// Group order: Doing before Todo before Done; empty groups omitted.
	iDoing := strings.Index(got, "## Doing")
	iTodo := strings.Index(got, "## Todo")
	iDone := strings.Index(got, "## Done")
	if iDoing < 0 || iTodo < 0 || iDone < 0 {
		t.Fatalf("missing a group heading:\n%s", got)
	}
	if !(iDoing < iTodo && iTodo < iDone) {
		t.Fatalf("groups out of order:\n%s", got)
	}
	if strings.Contains(got, "## Review") || strings.Contains(got, "## Blocked") {
		t.Fatalf("empty groups must be omitted:\n%s", got)
	}
	wantLine := "- [T-014](tasks/T-014-rate-limit-ingestion.md) Rate limit the ingestion endpoint `1/3` @claude"
	if !strings.Contains(got, wantLine) {
		t.Fatalf("doing line wrong; want %q in:\n%s", wantLine, got)
	}
	if !strings.Contains(got, "- [T-015](tasks/T-015-problem-json-envelope.md) Problem+JSON error envelope `0/4`\n") {
		t.Fatalf("todo line wrong:\n%s", got)
	}
	// An unassigned task carries no @name.
	if strings.Contains(got, "`0/4` @") {
		t.Fatalf("unassigned task should have no @name:\n%s", got)
	}
}

func TestRenderIndexDeterministic(t *testing.T) {
	root := t.TempDir()
	planTaskFile(t, root, "T-014-a.md", doingDoc)
	planTaskFile(t, root, "T-015-b.md", todoDoc)
	set, err := LoadTasks(root)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(RenderIndex(set), RenderIndex(set)) {
		t.Fatal("RenderIndex must be deterministic")
	}
}

func TestRenderIndexEmptySet(t *testing.T) {
	set := &TaskSet{Tasks: map[string]*Task{}}
	got := string(RenderIndex(set))
	if !strings.HasPrefix(got, "<!-- Generated by flow.") {
		t.Fatalf("empty index should still carry the header:\n%s", got)
	}
	if strings.Contains(got, "## ") {
		t.Fatalf("empty index should have no groups:\n%s", got)
	}
}
